import * as d3 from 'd3';

const interpolateList = [
  d3.interpolateBrBG,
  d3.interpolatePRGn,
  d3.interpolatePiYG,
  d3.interpolatePuOr,
  d3.interpolateRdBu,
  d3.interpolateRdGy,
  d3.interpolateRdYlBu,
  d3.interpolateRdYlGn,
  d3.interpolateSpectral,
  d3.interpolateBlues,
  d3.interpolateGreens,
  d3.interpolateGreys,
  d3.interpolateOranges,
  d3.interpolatePurples,
  d3.interpolateReds,
  d3.interpolateTurbo,
  d3.interpolateViridis,
  d3.interpolateInferno,
  d3.interpolateMagma,
  d3.interpolatePlasma,
  d3.interpolateCividis,
  d3.interpolateWarm,
  d3.interpolateCool,
  d3.interpolateCubehelixDefault,
  d3.interpolateBuGn,
  d3.interpolateBuPu,
  d3.interpolateGnBu,
  d3.interpolateOrRd,
  d3.interpolatePuBuGn,
  d3.interpolatePuBu,
  d3.interpolatePuRd,
  d3.interpolateRdPu,
  d3.interpolateYlGnBu,
  d3.interpolateYlGn,
  d3.interpolateYlOrBr,
  d3.interpolateYlOrRd,
  d3.interpolateRainbow,
  d3.interpolateSinebow,
];

export {interpolateList};
